services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    restart: always
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wp_volume:/var/www/html
    depends_on:
      - wordpress
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    networks:
      - inception
    volumes:
      - wp_volume:/var/www/html
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy
    restart: always
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    networks:
      - inception
    volumes:
      - db_volume:/var/lib/mysql/
    ports:
      - "3306:3306"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
  ftp:
    container_name: ftp
    build:
      context: ./requirements/bonus/ftp
      dockerfile: Dockerfile
    networks:
      - inception
    volumes:
      - wp_volume:/var/www/html
    ports:
      - 21:21
      - "40000-40010:40000-40010"
    env_file:
      - .env
    restart: always
  redis:
    container_name: redis
    depends_on:
      - wordpress
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
    env_file:
      - .env
    networks:
      - inception
    restart: always
  adminer:
    container_name: adminer
    depends_on:
      - wordpress
      - mariadb
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    networks:
      - inception
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: always
  flask:
    container_name: flask
    build:
      context: ./requirements/bonus/flask
      dockerfile: Dockerfile
    networks:
      - inception
    ports:
      - "3000:3000"
    restart: always
  cadvisor:
    container_name: cadvisor
    build:
      context: ./requirements/bonus/cadvisor
      dockerfile: Dockerfile
    networks:
      - inception
    ports:
      - "2843:2843"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always

volumes:
  wp_volume:
    driver: local
    driver_opts:
      device: /home/healeksa/data/wordpress
      o: bind
      type: none
  db_volume:
    driver: local
    driver_opts:
      device: /home/healeksa/data/mariadb
      o: bind
      type: none

networks:
  inception:
    driver: bridge
