services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    restart: always
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wp_volume:/var/www/html
    depends_on:
      - wordpress
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    networks:
      - inception
    volumes:
      - wp_volume:/var/www/html
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on:
      - mariadb
    restart: always
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    networks:
      - inception
    volumes:
      - db_volume:/var/lib/mysql/
    ports:
      - "3306:3306"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  wp_volume:
    driver: local
    driver_opts:
      device: /Users/hen/data/wordpress
      o: bind
      type: none
  db_volume:
    driver: local
    driver_opts:
      device: /Users/hen/data/mariadb
      o: bind
      type: none

networks:
  inception:
    driver: bridge
